name: chips
description: Add customizable and easy-to-use chip widgets to your Flutter apps for seamless user input and display.
version: 0.0.2

repository: https://github.com/adbonnin/flutter_chips
issue_tracker: https://github.com/adbonnin/flutter_chips/issues

topics:
  - chip

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  mockito: ^5.4.4
